# AppVeyor file
#   for Terraform Provider Sakuracloud

version: 1.0.0.{build}

branches:
  only:
    - master

skip_branch_with_pr: true

##############################################
# Environment Configuration
##############################################

install:
  # Install Git
  - git clone https://github.com/sacloud/chocolatey-terraform-provider-sakuracloud

##############################################
# Build Configuration
##############################################

build:
  # Set values
  - ps: echo "Start deploy script ..";
  - ps: $version          = ((Invoke-RestMethod https://api.github.com/repos/sacloud/terraform-provider-sakuracloud/releases/latest)[0] -split ";" | Select-String "tag_name=").ToString().Trim().Replace("tag_name=v", "");
  - ps: $versionText      = "terraform-provider-sakuracloud version ... v" + $version;
  - ps: echo $versionText;
  - ps: $appVeyorVersion  = $version + ${env:APPVEYOR_BUILD_VERSION}.Replace("1.0.0", "");
  - ps: set-item env:APPVEYOR_BUILD_VERSION -value $appVeyorVersion;
  - ps: $versionText      = "package version ... v" + $appVeyorVersion;
  - ps: echo $versionText;
  - ps: $zipX32           = 'terraform-provider-sakuracloud_' + $version + '_windows-386.zip';
  - ps: $zipX64           = 'terraform-provider-sakuracloud_' + $version + '_windows-amd64.zip';
  - ps: $url32            = 'https://github.com/sacloud/terraform-provider-sakuracloud/releases/download/v' + $version + '/terraform-provider-sakuracloud_' + $version + '_windows-386.zip';
  - ps: $url64            = 'https://github.com/sacloud/terraform-provider-sakuracloud/releases/download/v' + $version + '/terraform-provider-sakuracloud_' + $version + '_windows-amd64.zip';
  # Download zip files
  - ps: Invoke-WebRequest $url32 -OutFile .\x32.zip;
  - ps: Invoke-WebRequest $url64 -OutFile .\x64.zip;
  # Get hash values
  - ps: $hash32           = (Get-FileHash .\x32.zip -Algorithm SHA512).Hash;
  - ps: $hash64           = (Get-FileHash .\x64.zip -Algorithm SHA512).Hash;
  # Replace vlaues
  - ps: Set-Location -Path .\terraform-provider-sakuracloud;
  - ps: (Get-Content '.\terraform-provider-sakuracloud.nuspec' -Raw).Replace("__VERSION__", "$($appVeyorVersion)") | Out-File '.\terraform-provider-sakuracloud.nuspec';
  - ps: (Get-Content '.\tools\chocolateyinstall.ps1' -Raw).Replace("__URL_32__", "$($url32)").Replace("__URL_64__", "$($url64)").Replace("__HASH32__", $hash32).Replace("__HASH64__", $hash64) | Out-File '.\tools\chocolateyinstall.ps1';
  # Create chocolatey package
  - ps: choco pack;

##############################################
# Test Configuration
##############################################

test:
  # Check Install
  - ps: $packName = 'terraform-provider-sakuracloud';
  - ps: choco install $packName -s .\ -f;

##############################################
# Deployment Configuration
##############################################

deploy_script:
  # Push nupkg file
  - ps: $nupkgName        = (Get-ChildItem * -Include *.nupkg).Name;
  - ps: Push-AppveyorArtifact $nupkgName;
