# AppVeyor file
#   for Terraform Provider Sakuracloud

version: '{build}'

branches:
  only:
    - master
    - /feature*/

install:
  - ps: |
      Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version;
      $PSVersionTable;
      git --version;
      choco upgrade chocolatey -y;
      choco -v;

build_script:
  - ps: |
      $version          = ((Invoke-RestMethod https://api.github.com/repos/sacloud/terraform-provider-sakuracloud/releases/latest)[0] -split ";" | Select-String "tag_name=").ToString().Trim().Replace("tag_name=v", "");
      $appVeyorVersion  = $version + '.' + ${env:APPVEYOR_BUILD_VERSION};
      Update-AppveyorBuild -Version $appVeyorVersion
      set-item env:APPVEYOR_BUILD_VERSION -value $appVeyorVersion;
      $versionText      = "terraform-provider-sakuracloud version " + $version;
      echo $versionText;
      $versionText      = "package version " + $appVeyorVersion;
      echo $versionText;
      $url32            = 'https://github.com/sacloud/terraform-provider-sakuracloud/releases/download/v' + $version + '/terraform-provider-sakuracloud_' + $version + '_windows_386.zip';
      $url64            = 'https://github.com/sacloud/terraform-provider-sakuracloud/releases/download/v' + $version + '/terraform-provider-sakuracloud_' + $version + '_windows_amd64.zip';
      Invoke-WebRequest $url32 -OutFile .\x32.zip;
      Invoke-WebRequest $url64 -OutFile .\x64.zip;
      $hash32           = (Get-FileHash .\x32.zip -Algorithm SHA512).Hash;
      $hash64           = (Get-FileHash .\x64.zip -Algorithm SHA512).Hash;
      Set-Location -Path .\terraform-provider-sakuracloud;
      (Get-Content '.\terraform-provider-sakuracloud.nuspec' -Raw).Replace("__VERSION__", "$($appVeyorVersion)") | Out-File '.\terraform-provider-sakuracloud.nuspec' -Encoding utf8;
      (Get-Content '.\tools\chocolateyinstall.ps1' -Raw).Replace("__URL_32__", "$($url32)").Replace("__URL_64__", "$($url64)").Replace("__HASH32__", $hash32).Replace("__HASH64__", $hash64) | Out-File '.\tools\chocolateyinstall.ps1' -Encoding utf8;
      choco pack;

test_script:
  - ps: |
      $packName = 'terraform-provider-sakuracloud';
      choco install $packName -s .\ -f;
      choco uninstall $packName;

artifacts:
  - path: '.\terraform-provider-sakuracloud\*.nupkg'
  - path: '.\terraform-provider-sakuracloud\tools\*.ps1'
  - path: '.\terraform-provider-sakuracloud\terraform-provider-sakuracloud.nuspec'

# deploy_script:
#   - ps: |
#       $packName = 'terraform-provider-sakuracloud';
#       choco apikey --key ${env:CHOCO_API_KEY} --source https://push.chocolatey.org/
#       choco push $nupkgName --source https://push.chocolatey.org/
